### ISSUE TITLE
Tracks to edges greyed out

### ISSUE THREAD

**Issue by xBenjo** [ohitstom/spicetify-extensions#10]
I am on an old version of spotify (1.2.20.1216.ge7ab92f) and understand if it not worth your time fixing. I just use it for compatibility reasons.
When trying to move a track, them menu doesn't highlight and wont allow we to click anything. Maybe you could direct me to an older version of the extension idk. I have tried downloading from the marketplace and manually from gitgub.
![image](https://github.com/ohitstom/spicetify-extensions/assets/138199616/138f6f1d-fa62-4f09-937c-59a048d153e5)

**Comment by ohitstom** [comment]
yeah idk we only support latest versions unless you have a valid reason i suggest you update both, if you cant please inspect element and show me any errors

**Comment by xBenjo** [comment]
Yeah updating spotify breaks all my extensions that I use and inspect element doesn't work on this version. Thanks
