### ISSUE TITLE
quickQueue new spicetify version

### ISSUE THREAD

**Issue by Leffy02** [ohitstom/spicetify-extensions#11]
i've installed the latest version of spicetify and the quickQueue extention seems doesn't work

**Comment by ohitstom** [comment]
> i've installed the latest version of spicetify and the quickQueue extention seems doesn't work

what versions of spicetify and Spotify exactly, and are you using any other extensions etc

**Comment by Leffy02** [comment]
i'm using Spotify 1.2.35.663.gb699649e, Spicetify v2.36.4 marketplace version 1.0.1. The extentions i'm using are: quickQueue.js, fullAlbumDate.js, volumePercentageWrapper.js, power-bar.js, adblock.js, CoverAmbience.js, playlist-icons.js, beautiful-lyrics.js, star-ratings.js, fullScreenWrapper.js

**Comment by ohitstom** [comment]
> i'm using Spotify 1.2.35.663.gb699649e, Spicetify v2.36.4 marketplace version 1.0.1. The extentions i'm using are: quickQueue.js, fullAlbumDate.js, volumePercentageWrapper.js, power-bar.js, adblock.js, CoverAmbience.js, playlist-icons.js, beautiful-lyrics.js, star-ratings.js, fullScreenWrapper.js

this is probably an issue with playlist icons, or star ratings overwriting quick queue can you try removing them both and seeing if this fixes the issue

**Comment by Leffy02** [comment]
i've removed playlist icons and now it works, thanks

**Comment by ohitstom** [comment]
> i've removed playlist icons and now it works, thanks

I'll look into why they don't work together and get back to you if I find a fix
