### ISSUE TITLE
quickQueue button doesn't show up

### ISSUE THREAD

**Issue by walbjorn** [ohitstom/spicetify-extensions#12]
quickQueue button doesn't show up for me. it did until very recently. Screenshot attached.
<img width="738" alt="Spotify_17WKA5CL2V" src="https://github.com/ohitstom/spicetify-extensions/assets/62746266/f318dad1-75f4-4996-a200-52462147b2a1">

**Comment by ohitstom** [comment]
what versions are you on of spicetify and spotify, how have you installed quickQueue, and what other extensions / themes / snippets do you have

**Comment by walbjorn** [comment]
I was using a couple of extension and a theme, but I deleted them just now to test with only Quick Queue installed. the button still does not show up, sadly.

Version info as follows:

Spotify til Windows (32-bit)
1.2.36.955.gd8cc9372
Spicetify v2.36.9

**Comment by ohitstom** [comment]
you are using legacy hearts, i'll try to repair this functionality

**Comment by walbjorn** [comment]
ahhhh I see. I didn't intend to use legacy hearts/likes. do you happen to know how to revert this in my installation? no worries whatsoever if not.

regardless, thank you for your work, it's much appreciated :-)

**Comment by ohitstom** [comment]
if you open experimental features you can turn on aligned curation but you dont have to now that ive fixed it (Just need to wait for spicetify to merge)

**Comment by walbjorn** [comment]
ah, gotcha. afiirmative - I'll wait for the merge and enjoy the best of both worlds. cheers mate.
