### ISSUE TITLE
Quick Queue - Duplicate message

### ISSUE THREAD

**Issue by zeroma25** [ohitstom/spicetify-extensions#13]
message is duplicated when adding a track to the queue
![Снимок экрана 2024-05-05 215058](https://github.com/ohitstom/spicetify-extensions/assets/58146362/a7dddcdc-32cf-4e06-9801-404107a83f7b)

**Comment by ohitstom** [comment]
> message is duplicated when adding a track to the queue

I'm assuming they mean the same thing but in different languages? 

what are your spice and Spotify versions and what other stuff do you have installed

**Comment by zeroma25** [comment]
> I'm assuming they mean the same thing but in different languages?

Yes



> what are your spice and Spotify versions and what other stuff do you have installed

![Снимок экрана 2024-05-05 220118](https://github.com/ohitstom/spicetify-extensions/assets/58146362/3e0d2830-b737-4354-81b3-c238b34d51a1)
same on version 1.2.36
