### ISSUE TITLE
Placement of sleepTimer

### ISSUE THREAD

**Issue by brusvv** [ohitstom/spicetify-extensions#14]
Can you please make the extension moveable? Sometimes I'm screening the track or just using that at evening mostly, so most of the time it's visible next to the like button and is not used.

**Comment by ohitstom** [comment]
> Can you please make the extension moveable? Sometimes I'm screening the track or just using that at evening mostly, so most of the time it's visible next to the like button and is not used.

can you elaborate on what you mean by movable?

**Comment by brusvv** [comment]
![image](https://github.com/ohitstom/spicetify-extensions/assets/55412131/7440eb4b-aa58-41bb-936b-d72255aaa639)
I mean this button/icon of button. Anyway, it’s so close and might accidentally miss-click

**Comment by ohitstom** [comment]
the right side is cluttered enough as it is when people are using extensions, i dont think im going to change this functionality but i'll leave the issue open incase i reconsider

**Comment by brusvv** [comment]
Yes, there's a lot there, but that's the point. All of these can be described as tools or things that are used less often than like button

**Comment by brusvv** [comment]
It is unlikely that people on the desktop look at the time more often than at the cursor. Imagine if the close button was next to the start menu.

![image](https://github.com/ohitstom/spicetify-extensions/assets/55412131/b48f5f4d-a433-4949-82f9-c45b3e226658)
What about move it a little further or give people to choose the placement?

**Comment by brusvv** [comment]
> im following spotifys design philosphy not what spicetify devs prefer to do, all of spotifys own buttons on the right side either open a new page or a new sidebar, all the ones on the left open a popup or need a visual aspect

the button and slider of sound don't open anything

**Comment by ohitstom** [comment]
> It is unlikely that on the desktop people look at the time more often than at the cursor. Imagine if the close button was next to the start menu.

this is a big skill issue, just dont misclick? the button to open the album is also right next to the heart button

**Comment by brusvv** [comment]
> this is a big skill issue, just dont misclick? the button to open the album is also right next to the heart button

what about you're talking? Album is opening rn when you click the cover of album
![image](https://github.com/ohitstom/spicetify-extensions/assets/55412131/7c826fe8-34fd-471b-9513-0e795f7b35a3)

Personally, my problem is not the missclick, but the fact that it is always in front of my eyes. Be polite next time, I wasn't being rude to you. I think your problem is that you are too stubborn and can't hear different opinion from yours

**Comment by ohitstom** [comment]
>> Personally, my problem is not the missclick, but the fact that it is always in front of my eyes
half the point of a timer is being able to see how long is left on the timer at a glance

>> I think your problem is that you are too stubborn and can't hear different opinion from yours
I make extensions for myself, im happy to add features but im not completely rewriting it just because of one persons differing ideals on design, i think the way it is currently is good

You are happy to make a fork of this repo and move it yourself, i will potentially consider a way of hiding the timer text (00:00) with a shift click but im not moving the button itself
