### ISSUE TITLE
[Feature Request] Right click on Quick Queue button to add to play next. 

### ISSUE THREAD

**Issue by cariosa** [ohitstom/spicetify-extensions#16]
I seem to use [Play next](https://github.com/daksh2k/Spicetify-stuff) feature more than 'add to queue'. So this feature would save me 1s of time every time I add a song to queue. I think many people would benefit from this feature as well.

**Comment by ohitstom** [comment]
can do

**Comment by cariosa** [comment]
> can do, how does holding shift sound and it changes its icon to signify or is that less intuitive?

mmm both options has their advantages,
with holding shift, you'd know which option you're using.
wtih right click, you don't have to reach the keyboard.

how 'bout implementing it both ways? don't know about the UX part of this.
