### ISSUE TITLE
[Feature Request] extend 'track to edges' feature to tracks in queue

### ISSUE THREAD

**Issue by cariosa** [ohitstom/spicetify-extensions#17]
This feature helps when you wanna rearrange tracks in queue, especially when the queue is long.

Thanks to all the extensions btw, some of these are really helpful.

**Comment by ohitstom** [comment]
> This feature helps when you wanna rearrange tracks in queue, especially when the queue is long.

i will if i can, depends on what spotify lets me do 👍🏻

**Comment by ohitstom** [comment]
let me know if you have any issues with this feature, i havent really done extensive testing 👍🏻

**Comment by cariosa** [comment]
This works as expected!
kudos for working on this, very helpful.
