### ISSUE TITLE
Feature: spotifyBackup: Auto Backup

### ISSUE THREAD

**Issue by rahaaatul** [ohitstom/spicetify-extensions#20]
## Description
Backup Spicetify data in a file automatically at set time.

### Configuration should include:

- Backup at startup: `True` | `False`.
    - Backup Delay: `X` Seconds/Minutes.
- Backup Frequency: `X` Minute/Hour/Day.
- Backup location: Primarily in spicetify folder: `%appdata%/spicetify`.

**Comment by ohitstom** [comment]
as far as I'm aware it's not possible to write to the file system from Spotify, the best I can do is some sort of remote service like cloud storage or discord webhooks.

you got any ideas?

**Comment by rahaaatul** [comment]
> As far as I'm aware it's not possible to write to the file system from Spotify
- Damn! That’s a big limitation. Are you sure about that? Spotify can download files, which is essentially writing data to the system, right?

> The best I can do is some sort of remote service like cloud storage or discord webhooks.
- Webhook is a great idea! But where will it save? Not everyone has a server. Sure, they can make one. But not ideal.
- Storing it in cloud storage is an even greater idea. Everyone has a cloud service they use; most users use Google Drive, iCloud or OneDrive. So, I think if you can do both, that's great. If not, this one should be the practical choice.

**Comment by ohitstom** [comment]
please let me know if you have any issues, read the updated readme if you are struggling with setup!

**Comment by rahaaatul** [comment]
I apologize for the late reply. 

> please let me know if you have any issues, read the updated readme if you are struggling with setup!

You did a really great job with this one. It was so easy to follow the `README` and setup the gist backup. 

I have tried and tested the extension; it's working perfectly! 🥳The backup extension feels more productive now. Less fear of losing it.

I have a question (not related to this topic), is it possible to theme the window controls like MAC OS? I've been trying to find selector for it to change the shape of it. But I wasn't able to find any with `inspect element` (keep in mind I'm a beginner and have a very little knowledge on html/css/js). 

Thank you.

**Comment by ohitstom** [comment]
glad to hear it works for you

in regards to the windows controls you cannot since Spotify uses the chrome embedded framework controls
