### ISSUE TITLE
noContol.js Works, but it doesn't change top bar layout

### ISSUE THREAD

**Issue by Trixfinity** [ohitstom/spicetify-extensions#24]
The No Controls extensions suddenly started to work, but it doesn't seem to shift any icons to the right as it used to. It's doable in Inspect, but I can't make a snippet to make it do it automatically.

![image](https://github.com/user-attachments/assets/3b9b9dea-3d26-4335-aad1-94bc89f2a9ef)
![image](https://github.com/user-attachments/assets/fae59cde-3ee1-4bc5-a35b-00c24f9f5710)
![image](https://github.com/user-attachments/assets/1384e4b7-cd33-40b5-8f87-01bd2690f81e)

**Comment by ohitstom** [comment]
I'm a little confused can you elaborate

**Comment by Trixfinity** [comment]
The extension gets rid of the Controls, but the top bar doesn't shift in response to it. It stays in the same place even though there's space to the right of the bar. 

So, whenever the padding is turned off, it correctly uses the entirety of the space on top without the controls as it used to before
