### ISSUE TITLE
[SUGGESTION] Leaving playback bar visible in immersive view

### ISSUE THREAD

**Issue by th3r1ko** [ohitstom/spicetify-extensions#25]
I would be grateful to you if you would make a setting (or a cycle of views, for example without a bar and with it) for Immersive view, so that you can leave the playback bar visible

**Comment by ohitstom** [comment]
i will add preference options in a setting menu, for example:
- hide playbar
- hide library
- hide topbar
- hide right panel

then when you enable and disable as normal it will use your configuration settings

**Comment by th3r1ko** [comment]
Seems perfect! Thanks a lot!

**Comment by ohitstom** [comment]
i havent added it yet, just was throwing ideas out there, in the works of doing this and will close the issue (Which will update you via email ive done it) when its done!
