### ISSUE TITLE
Immersive view not working

### ISSUE THREAD

**Issue by thegoldknight** [ohitstom/spicetify-extensions#3]
Clicking the immersive view button does nothing. 
I'm on Mac.

**Comment by ohitstom** [comment]
send over your config

**Comment by ohitstom** [comment]
your version info is empty can you find it for me

**Comment by thegoldknight** [comment]
<img width="261" alt="image" src="https://github.com/ohitstom/spicetify-extensions/assets/135397968/1581aeaa-8d26-4cb5-8c48-c1fd5fa52aaa">

**Comment by ohitstom** [comment]
> <img width="261" alt="image" src="https://github.com/ohitstom/spicetify-extensions/assets/135397968/1581aeaa-8d26-4cb5-8c48-c1fd5fa52aaa">
> 

weird, can you check console for errors to do with the extension, spicetify enable-devtools, Ctrl shift i

**Comment by thegoldknight** [comment]
<img width="1438" alt="image" src="https://github.com/ohitstom/spicetify-extensions/assets/135397968/3cb0389e-d8a1-4e79-b011-5542095208ec">

**Comment by thegoldknight** [comment]
I might just reinstall Spotify and spicetify completely; it's acting really weird on my end.

**Comment by ohitstom** [comment]
fixed as of #[d6bb27b](https://github.com/ohitstom/spicetify-extensions/commit/d6bb27bc3c361848b45ff027311924f8e2c9f755)
