### ISSUE TITLE
[SUGGESTION] Add a button to toggle Immersive View

### ISSUE THREAD

**Issue by thegoldknight** [ohitstom/spicetify-extensions#4]
It would be nice if you could press a button to activate immersive view, and maybe add a config key by right clicking the icon.

**Comment by ohitstom** [comment]
a hotkey would be possible, not sure about a settings menu thats a lot of work for such a simple feature, what kind of hotkey were you thinking?

**Comment by thegoldknight** [comment]
Maybe the I or V button since T and F might conflict with the full screen extension. And maybe the esc key to untoggle it?

**Comment by ohitstom** [comment]
went with ctrl + i, and escape for exiting ontop of this toggle @thegoldknight
