### ISSUE TITLE
Clicking the clock doesn't do anything

### ISSUE THREAD

**Issue by AdrisAz** [ohitstom/spicetify-extensions#6]
I can't seem to open any setting window to modify the clock display settings.

**Comment by ohitstom** [comment]
> I can't seem to open any setting window to modify the clock display settings.

unfortunately I have not had time to finish this extension yet, I'll get to it as soon as I can sorry

**Comment by AdrisAz** [comment]
No worries, thank you!

**Comment by ohitstom** [comment]
> No worries, thank you!

if i get some time today i might work on it, what kind of display options were you looking for? my initial thoughts are:
- removal of seconds
- hiding pm/am
- 24hours and 12hour

anything else you think would be handy?

**Comment by AdrisAz** [comment]
The option to remove seconds would be appreciated! :)
