### ISSUE TITLE
Playbar Clock extension: Incorrect 24h format.

### ISSUE THREAD

**Issue by UP5-5** [ohitstom/spicetify-extensions#7]
Incorrect format.
![Goofy ahh time](https://github.com/ohitstom/spicetify-extensions/assets/126914274/a5e6be89-4bb8-491c-8679-c2c07da8292f)

**Comment by ohitstom** [comment]
click on it

**Comment by ohitstom** [comment]
oh 24 lol

**Comment by ohitstom** [comment]
should be fixed, added more options too.
