### ISSUE TITLE
Immersive mode automatically enabled

### ISSUE THREAD

**Issue by gensimone** [ohitstom/spicetify-extensions#9]
Is there a way to automatically enable immersive mode when launching Spotify?

**Comment by ohitstom** [comment]
not currently, i will make this a feature.

question is would it make more sense to cache the state so if you close Spotify with immersive view enabled it will save that, or make it a separate setting menu....

what would fit your use case better?

**Comment by g3nsy** [comment]
Having a separate menu would be more intuitive (?)

**Comment by ohitstom** [comment]
> Having a separate menu would be more intuitive (?)

https://github.com/spicetify/spicetify-cli/issues/2757
waiting on an update on this issue to proceed
